@startuml teste

left to right direction

actor Freelancer
actor Client
actor Administrator
actor System

usecase "Send Notification" as UC44

System -- UC44 

rectangle "Profile Management" {
  usecase "Create/Update Profile" as UC1
  usecase "Verify Profile" as UC31
  usecase "Update Availability" as UC3
  usecase "Add/Update Work Sample" as UC2
  usecase "Add/Update Security Specializations" as UC4
  usecase "Add/Update Location"
  usecase "Add/Update Education" as UC26
  usecase "Add/Update Certification" as UC27
  usecase "Add/Update Language" as UC28
  usecase "Add/Update Work Experience" as UC29
  usecase "Add/Update Payment Methods" as UC20
}

rectangle "Project Management" {
  usecase "Submit Proposal" as UC6
  usecase "Create/Manage Project" as UC7
  usecase "Manage Work Items" as UC8
  usecase "Review/Accept Proposals" as UC9
}

rectangle "Communication" {
  usecase "Initiate Chat" as UC10
  usecase "Send Message" as UC11
  usecase "Share File" as UC12
  usecase "View Chat History" as UC13
}

rectangle "Feedback" {
  usecase "Provide Feedback/Reviews" as UC17
}

rectangle "Administrative" {
  usecase "Manage Project Categories" as UC22
  usecase "Manage Technologies" as UC33
  usecase "Verify Freelancer Profile" as UC34
  usecase "Approve Freelancer Profile" as UC35
}

rectangle "Search and Browse" {
  usecase "Search for Projects" as UC5
  usecase "Browse Freelancer Profiles" as UC25
}

Freelancer -- UC1
Freelancer -- UC2
Freelancer -- UC3
Freelancer -- UC4
Freelancer -- UC26
Freelancer -- UC27
Freelancer -- UC28
Freelancer -- UC29
Freelancer -- UC31
Freelancer -- UC5
Freelancer -- UC6
Freelancer -- UC10
Freelancer -- UC11
Freelancer -- UC12
Freelancer -- UC13
Freelancer -- UC17

Client -- UC7
Client -- UC8
Client -- UC9
Client -- UC10
Client -- UC11
Client -- UC12
Client -- UC13
Client -- UC17
Client -- UC20
Client -- UC25

Administrator -- UC33
Administrator -- UC22
Administrator -- UC34
Administrator -- UC35

UC1 ..> UC5 : <<includes>>
UC1 ..> UC6 : <<includes>>
UC7 ..> UC9 : <<includes>>
UC10 ..> UC11 : <<extends>>
UC10 ..> UC12 : <<extends>>
UC10 ..> UC13 : <<extends>>

@enduml