@startuml usecase diagram
left to right direction

actor Usuário as User
actor Freelancer
actor Cliente

usecase "Registrar" as UC_Registrar
usecase "Login" as UC_Login
usecase "Esqueceu a Senha" as UC_EsqueceuSenha
usecase "Recuperar Senha" as UC_RecuperarSenha
usecase "Gerenciar Conta" as UC_GerenciarConta

usecase "Gerenciar Perfil" as UC_GerenciarPerfil

usecase "Enviar Proposta" as UC_EnviarProposta
usecase "Buscar Projetos" as UC_BuscarProjetos
usecase "Gerenciar Projetos Ativos" as UC_GPA
usecase "Gerenciar Minhas Propostas" as UC_GMPropostas
usecase "Gerenciar Convites" as UC_GerenciarConvites
usecase "Gerenciar Mensagens" as UC_GerenciarMensagens1

usecase "Gerenciar Meus Projetos" as UC_GMProjetos
usecase "Gerenciar Propostas Recebidas" as UC_GPR
usecase "Convidar Freelancer" as UC_ConvidarFreelancer
usecase "Buscar Freelancers" as UC_BuscarFreelancers
usecase "Gerenciar Mensagens" as UC_GerenciarMensagens2

User --> UC_GerenciarConta
User --> UC_Login
User --> UC_EsqueceuSenha
User --> UC_Registrar

Cliente --|> User
Freelancer --|> User

UC_EsqueceuSenha --> UC_RecuperarSenha : <<include>>
UC_GerenciarConta --> UC_GerenciarPerfil : <<include>>

UC_BuscarFreelancers <.. UC_ConvidarFreelancer : <<extend>>  
UC_BuscarProjetos <.. UC_EnviarProposta : <<extend>>

Freelancer --> UC_BuscarProjetos
Freelancer --> UC_GerenciarConvites
Freelancer --> UC_GerenciarMensagens1
Freelancer --> UC_GPA
Freelancer --> UC_GMPropostas

Cliente --> UC_BuscarFreelancers
Cliente --> UC_GerenciarMensagens2
Cliente --> UC_GMProjetos
Cliente --> UC_GPR

@enduml 