@startuml usecase diagram
left to right direction

actor Usuário as User
actor Freelancer
actor Cliente

usecase "Registrar" as UC_Registrar
usecase "Login" as UC_Login
usecase "Recuperar Senha" as UC_RecuperarSenha
usecase "Gerenciar Conta" as UC_GerenciarConta

usecase "Gerenciar Perfil" as UC1

usecase "Enviar Proposta" as UC6
usecase "Buscar Projetos" as UC5
usecase "Gerenciar Projetos" as UC13
usecase "Gerenciar Propostas" as UC14
usecase "Gerenciar Convites" as UC10
usecase "Gerenciar Mensagens" as UC11

usecase "Gerenciar Projeto" as UC7
usecase "Gerenciar Propostas" as UC9
usecase "Convidar Freelancer" as UC8
usecase "Gerenciar Convites" as UC35
usecase "Buscar Freelancers" as UC25
usecase "Gerenciar Mensagens" as UC12

User --> UC_Registrar
User --> UC_Login
User --> UC_RecuperarSenha
User --> UC_GerenciarConta

Cliente --|> User
Freelancer --|> User

UC_GerenciarConta --> UC1 : <<include>>

UC5 <.. UC6 : <<extend>>  
UC25 <.. UC8 : <<extend>>

Freelancer --> UC5
Freelancer --> UC10
Freelancer --> UC11
Freelancer --> UC13
Freelancer --> UC14

Cliente --> UC7
Cliente --> UC9
Cliente --> UC35
Cliente --> UC25
Cliente --> UC12

@enduml 